// <auto-generated />
namespace GoodLife.InfraEstrutura.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Cidade : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Cidade));
        
        string IMigrationMetadata.Id
        {
            get { return "201708240105462_Cidade"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
